import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, within } from "storybook/test";
import { controlNames, defaultArgs, toArgTypes, governedFieldIds } from "@bbox-ui/schema";
import {
  Pill,
  PILL_FIELDS,
  PILL_PRESETS,
  type AppearanceState,
  type Lens,
  type PillLineThickness,
  type Tone,
} from "@bbox-ui/core";
import type { ComponentProps } from "react";

/**
 * T1 Lane L: Pill, the flagship cascade example. `argTypes`/`args` below
 * are GENERATED from `PILL_FIELDS` (packages/bbox-ui/src/pill.fields.ts) —
 * the SAME array `demos/inspector`'s trace panel reads. Add a field there
 * and both surfaces pick it up; nothing here is kept in sync by hand.
 *
 * The cast on `args` is deliberate — same T0 `Port.stories.tsx` shape:
 * `defaultArgs` returns the generic `Record<string, FieldValue>` every
 * schema-driven component shares, one degree looser than `Pill`'s own
 * literal-union prop types. `pill.fields.test.ts` proves the values agree.
 */
const meta = {
  title: "Components/Pill",
  component: Pill,
  args: defaultArgs(PILL_FIELDS, PILL_PRESETS) as Partial<ComponentProps<typeof Pill>>,
  argTypes: toArgTypes(PILL_FIELDS),
} satisfies Meta<typeof Pill>;

export default meta;

type Story = StoryObj<typeof meta>;

const TONE_FIELD = PILL_FIELDS.find((f) => f.id === "tone")!;
const LENS_FIELD = PILL_FIELDS.find((f) => f.id === "lens")!;
const LINE_THICKNESS_FIELD = PILL_FIELDS.find((f) => f.id === "lineThickness")!;

/**
 * Pill has no "click the dot" interaction (it paints nothing but its own
 * shell) — per §6's own rule for such components, the play function
 * instead asserts the rendered DOM matches the args this story was
 * actually rendered with.
 */
export const Primary: Story = {
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    const pill = canvasElement.querySelector('[data-slot="pill"]');
    if (!(pill instanceof HTMLElement)) {
      throw new Error('expected a [data-slot="pill"] element in the DOM');
    }
    await expect(pill.getAttribute("data-state")).toBe(args.state);
    await expect(pill.getAttribute("data-tone")).toBe(args.tone);
    if (args.children != null && args.children !== "") {
      await expect(canvas.getByText(String(args.children))).toBeInTheDocument();
    }
  },
};

/**
 * One row per real `AppearanceState`, generated by mapping over
 * `PILL_PRESETS` — never hand-written per preset (§6 item 3). Adding a
 * preset to `PILL_PRESETS` changes this story's rows, this story's
 * excluded controls, AND the product inspector's preset picker, with zero
 * edits to this file.
 */
const GOVERNED = controlNames(PILL_FIELDS, governedFieldIds(PILL_PRESETS));
// The SELECTOR is excluded too, not just the fields the presets govern. This
// story paints one row per preset and sets `state` per row, so a live State
// control moved nothing — the same "a control that does nothing reads as
// broken" complaint that started this whole thread, one level along. Every
// gallery story here excludes the axis it is sweeping; this one sweeps the
// selector itself.
const PRESET_SELECTORS = controlNames(
  PILL_FIELDS,
  Array.from(new Set(PILL_PRESETS.map((preset) => preset.selector))),
);
export const Presets: Story = {
  parameters: { controls: { exclude: [...GOVERNED, ...PRESET_SELECTORS] } },
  render: (args) => (
    <div style={{ display: "flex", flexDirection: "column", gap: 12, alignItems: "flex-start" }}>
      {PILL_PRESETS.map((preset) => (
        // WHY `...args` and not `presetArgs(...)`: this story fixes only the
        // SELECTOR per row; everything else has to come from the Controls
        // panel, which is Zach's own rule for a gallery ("sweep one field,
        // take the rest from args"). Building each row from defaults instead
        // left seven live controls — tone, lens, lensBefore, line thickness,
        // both opacities, the label — moving nothing at all, which is the
        // same "a control that does nothing reads as broken" complaint that
        // started this thread.
        <Pill
          key={preset.id}
          {...(args as ComponentProps<typeof Pill>)}
          {...({ [preset.selector]: preset.id } as ComponentProps<typeof Pill>)}
        >
          {preset.label}
        </Pill>
      ))}
    </div>
  ),
};

const sweep = (fieldId: string) => ({
  controls: { exclude: controlNames(PILL_FIELDS, [fieldId]) },
});

/** Every real Tone, including `neutral` (state drives the paint). */
export const AllTones: Story = {
  parameters: sweep("tone"),
  render: (args) => (
    <div style={{ display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
      {TONE_FIELD.options!.map((option) => (
        <Pill {...args} key={option.value} tone={option.value as Tone}>
          {args.children ?? option.label}
        </Pill>
      ))}
    </div>
  ),
};

/** Every real Lens value from the shared bundle. */
export const AllLenses: Story = {
  parameters: sweep("lens"),
  render: (args) => (
    <div style={{ display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
      {LENS_FIELD.options!.map((option) => (
        <Pill {...args} key={option.value} lens={option.value as Lens}>
          {args.children ?? option.label}
        </Pill>
      ))}
    </div>
  ),
};

/** Every real line-thickness rung — the one ungoverned segmented field a
 * preset never touches. */
export const AllLineThicknesses: Story = {
  parameters: sweep("lineThickness"),
  render: (args) => (
    <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
      {LINE_THICKNESS_FIELD.options!.map((option) => (
        <Pill {...args} key={option.value} lineThickness={option.value as PillLineThickness}>
          {args.children ?? option.label}
        </Pill>
      ))}
    </div>
  ),
};

/**
 * The bare shell — no label. `Pill`'s real prop has no destructured
 * default for `children`; omitting it renders the outline/fill alone.
 */
export const NoLabel: Story = {
  args: { children: undefined, state: "wired" as AppearanceState },
};
