packages:
  - packages/*
  - apps/playground
  - apps/docs
  - demos/reactflow
  - demos/tldraw
  - demos/scene
  - demos/compare
  - demos/compare-view
  - demos/dndkit-lab
allowBuilds:
  esbuild: true
  msw: false
