/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  "index": {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  "style": {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  "button": {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/button.tsx",
      type: "registry:ui"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "port-demo": {
    name: "port-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/examples/port-demo.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/port-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "port-layouts": {
    name: "port-layouts",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/examples/port-layouts.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/port-layouts.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "port-sizes": {
    name: "port-sizes",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/examples/port-sizes.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/port-sizes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "block-demo": {
    name: "block-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/examples/block-demo.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/block-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "block-with-ports": {
    name: "block-with-ports",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/examples/block-with-ports.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/block-with-ports.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  }